version: 2

models:
  - name: stg_policies
    description: Cleaned policy data for insurance analytics
    columns:
      - name: policy_number
        tests:
          - unique
          - not_null
      - name: policy_bind_date
        tests:
          - not_null
      - name: policy_state
        tests:
          - accepted_values:
              values: ['OH', 'IN', 'IL', 'PA', 'NY', 'SC', 'VA', null]
  - name: stg_customers
    description: Cleaned customer data for insurance analytics
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: insured_sex
        tests:
          - accepted_values:
              values: ['MALE', 'FEMALE']
      - name: age
        tests:
          - dbt_utils.expression_is_true:
              expression: " BETWEEN 18 AND 100"